apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ticket-booking-microserice
build:
  artifacts:
    - image: irhadudheen/ticket-auth
      context: auth
      docker:
        dockerfile: dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
